name: Build APK Manual

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Release (${{ matrix.variant }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [foss, gms]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-cleanup: on-success

      - name: Setup and Generate Protobuf
        uses: ./.github/actions/setup-protobuf

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Universal Release APK
        run: ./gradlew --console=plain assembleUniversal${{ matrix.variant == 'foss' && 'Foss' || 'Gms' }}Release --warning-mode summary
        env:
          PULL_REQUEST: "false"
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_SECRET: ${{ secrets.LASTFM_SECRET }}

      - name: Sign APK
        if: secrets.KEYSTORE != null
        uses: ilharp/sign-android-release@v2.0.0
        with:
          releaseDir: app/build/outputs/apk/universal${{ matrix.variant == 'foss' && 'Foss' || 'Gms' }}/release/
          signingKey: ${{ secrets.KEYSTORE }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Move signed APK
        if: secrets.KEYSTORE != null
        run: |
          OUTPUT_DIR="app/build/outputs/apk/universal${{ matrix.variant == 'foss' && 'Foss' || 'Gms' }}/release"
          mkdir -p "$OUTPUT_DIR/out"
          if [ "${{ matrix.variant }}" = "gms" ]; then
            TARGET_NAME="app-universal-with-Google-Cast.apk"
          else
            TARGET_NAME="app-universal-release.apk"
          fi
          find "$OUTPUT_DIR" -name "*-signed.apk" -o -name "*-unsigned-signed.apk" | xargs -I{} mv {} "$OUTPUT_DIR/out/$TARGET_NAME"

      - name: Move unsigned APK
        if: secrets.KEYSTORE == null
        run: |
          OUTPUT_DIR="app/build/outputs/apk/universal${{ matrix.variant == 'foss' && 'Foss' || 'Gms' }}/release"
          mkdir -p "$OUTPUT_DIR/out"
          if [ "${{ matrix.variant }}" = "gms" ]; then
            TARGET_NAME="app-universal-with-Google-Cast-unsigned.apk"
          else
            TARGET_NAME="app-universal-release-unsigned.apk"
          fi
          find "$OUTPUT_DIR" -name "*.apk" | xargs -I{} mv {} "$OUTPUT_DIR/out/$TARGET_NAME"

      - name: Upload APK
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.variant == 'gms' && 'app-universal-with-Google-Cast' || 'app-universal-release' }}
          path: app/build/outputs/apk/universal${{ matrix.variant == 'foss' && 'Foss' || 'Gms' }}/release/out/*
